from fontTools.ttLib import TTFont
from .utils import rm_extension
import textwrap

class ASS:
    def __init__(self, video_data, config):
        self.video_data = video_data
        self.config = config

        
    def write_script(self):
        font_name = self.get_font_name()
        
        header = f"""\
        [Script Info]
        ; Script Generated by Karasub
        ScriptType: v4.00+
        PlayResX: {self.video_data["resX"]}
        PlayResY: {self.video_data["resY"]}
        
        [V4+ Styles]
        Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        Style: CustomKaraoke,{font_name},{self.video_data["font_size"]},{self.config["primary_color"]},{self.config["secondary_color"]},{self.config["outline_color"]},{self.config["bg_color"]},-1,0,0,0,100,100,0,0,1,2.66667,0,2,7,7,33,1
        """
        
        body = textwrap.dedent(f"""\
        {header}
        [Events]
        Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        """)
        
        for line in self.video_data["transcript"]:
            start_time = self.sec_to_hms(line["start"])
            end_time = self.sec_to_hms(line["end"])
            
            dialogue = f"Dialogue: 0,{start_time},{end_time},CustomKaraoke,,0,0,0,,"
            
            for word in line["words"]:
                ceptisec = (word["end"] - word["start"]) * 100
                dialogue += f"{{\k{ceptisec}}}{word["word"]} "
            
            dialogue = dialogue.strip() + "\n"
            body += dialogue
            
        return self.script_to_ass(body)
            
    def script_to_ass(self, body):
        path = "temp/" + rm_extension(self.video_data["name"]) + ".ass"
        
        with open(path, "w") as file:
            file.write(body)
            
        return path
        
    def sec_to_hms(self, total_sec):
        mins, secs = divmod(total_sec, 60)
        hours, mins = divmod(mins, 60)
        
        hours = int(hours)
        mins = int(mins)

        return f"{hours:01d}:{mins:02d}:{secs}"        

    def get_font_name(self):
        font = TTFont(self.config["font_style"])
        name_table = font["name"]
        
        for record in name_table.names:
            if record.nameID == 4:
                return record.toUnicode()
            
        return "Unknown"